# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Chocolatey Action
      uses: crazy-max/ghaction-chocolatey@v1.2.2
      with:
        args: install cmake ActivePerl python2 ruby git svn patch diffutils gperf -y
   
    - name: install pywin32
      run: pip install pywin32
      
    - name: build
      run: perl Tools/Scripts/build-webkit --jsc-only --release
      
    

